package postgres

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"midigator/internal/domain"
)

// NotificationRepository implements domain.NotificationRepository with raw SQL.
// Notifications carry their own tenant_id, but the per-user read endpoints scope
// by user_id (a user belongs to exactly one tenant). The id column is a UUID
// generated by Postgres via gen_random_uuid().
type NotificationRepository struct {
	pool *pgxpool.Pool
}

func NewNotificationRepository(pool *pgxpool.Pool) *NotificationRepository {
	return &NotificationRepository{pool: pool}
}

// notificationCols is the full projection; nullable text/fk/timestamp columns
// scan into a plain string (COALESCE'd) or pointers, mirroring the chargeback repo.
const notificationCols = `id, user_id, tenant_id, type, title, body,
	COALESCE(notifiable_type,''), notifiable_id, read_at, created_at`

func scanNotification(row pgx.Row) (*domain.Notification, error) {
	var n domain.Notification
	err := row.Scan(
		&n.ID, &n.UserID, &n.TenantID, &n.Type, &n.Title, &n.Body,
		&n.NotifiableType, &n.NotifiableID, &n.ReadAt, &n.CreatedAt,
	)
	if err != nil {
		return nil, err
	}
	return &n, nil
}

func (r *NotificationRepository) Create(ctx context.Context, n *domain.Notification) (*domain.Notification, error) {
	const q = `INSERT INTO notifications
		(id, user_id, tenant_id, type, title, body, notifiable_type, notifiable_id)
		VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7)
		RETURNING id, created_at`
	err := r.pool.QueryRow(ctx, q,
		n.UserID, n.TenantID, n.Type, n.Title, n.Body, nullable(n.NotifiableType), n.NotifiableID,
	).Scan(&n.ID, &n.CreatedAt)
	if err != nil {
		return nil, fmt.Errorf("insert notification: %w", mapDBError(err))
	}
	return n, nil
}

func (r *NotificationRepository) ListByUser(ctx context.Context, userID int64, unreadOnly bool, limit int) ([]domain.Notification, error) {
	if limit <= 0 || limit > 200 {
		limit = 50
	}
	where := "WHERE user_id = $1"
	if unreadOnly {
		where += " AND read_at IS NULL"
	}
	q := fmt.Sprintf(`SELECT %s FROM notifications %s ORDER BY created_at DESC LIMIT $2`, notificationCols, where)
	rows, err := r.pool.Query(ctx, q, userID, limit)
	if err != nil {
		return nil, fmt.Errorf("list notifications: %w", err)
	}
	defer rows.Close()

	var out []domain.Notification
	for rows.Next() {
		n, err := scanNotification(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, *n)
	}
	return out, rows.Err()
}

func (r *NotificationRepository) UnreadCount(ctx context.Context, userID int64) (int, error) {
	var n int
	err := r.pool.QueryRow(ctx,
		`SELECT COUNT(*) FROM notifications WHERE user_id = $1 AND read_at IS NULL`, userID).Scan(&n)
	if err != nil {
		return 0, fmt.Errorf("count unread notifications: %w", err)
	}
	return n, nil
}

func (r *NotificationRepository) MarkRead(ctx context.Context, userID int64, id string) error {
	tag, err := r.pool.Exec(ctx,
		`UPDATE notifications SET read_at = now() WHERE user_id = $1 AND id = $2 AND read_at IS NULL`,
		userID, id)
	if err != nil {
		return fmt.Errorf("mark notification read: %w", err)
	}
	if tag.RowsAffected() == 0 {
		// Either it doesn't exist (for this user) or it was already read; treat a
		// missing row as not-found so the handler returns 404.
		var exists bool
		if e := r.pool.QueryRow(ctx,
			`SELECT EXISTS(SELECT 1 FROM notifications WHERE user_id = $1 AND id = $2)`,
			userID, id).Scan(&exists); e == nil && !exists {
			return domain.NotFound("notification")
		}
	}
	return nil
}

func (r *NotificationRepository) MarkAllRead(ctx context.Context, userID int64) error {
	_, err := r.pool.Exec(ctx,
		`UPDATE notifications SET read_at = now() WHERE user_id = $1 AND read_at IS NULL`, userID)
	if err != nil {
		return fmt.Errorf("mark all notifications read: %w", err)
	}
	return nil
}

// ---- notification_settings -------------------------------------------------

const notificationSettingsCols = `user_id, channel, chargeback_new, chargeback_result,
	prevention_new, daily_digest, weekly_report`

func scanNotificationSettings(row pgx.Row) (*domain.NotificationSettings, error) {
	var s domain.NotificationSettings
	err := row.Scan(
		&s.UserID, &s.Channel, &s.ChargebackNew, &s.ChargebackResult,
		&s.PreventionNew, &s.DailyDigest, &s.WeeklyReport,
	)
	if err != nil {
		return nil, err
	}
	return &s, nil
}

func (r *NotificationRepository) GetSettings(ctx context.Context, userID int64) (*domain.NotificationSettings, error) {
	row := r.pool.QueryRow(ctx,
		`SELECT `+notificationSettingsCols+` FROM notification_settings WHERE user_id = $1`, userID)
	s, err := scanNotificationSettings(row)
	if errors.Is(err, pgx.ErrNoRows) {
		// No saved preferences yet: return sensible defaults rather than erroring.
		return &domain.NotificationSettings{
			UserID:           userID,
			Channel:          "both",
			ChargebackNew:    true,
			ChargebackResult: true,
			PreventionNew:    true,
		}, nil
	}
	if err != nil {
		return nil, fmt.Errorf("get notification settings: %w", err)
	}
	return s, nil
}

func (r *NotificationRepository) UpsertSettings(ctx context.Context, s *domain.NotificationSettings) (*domain.NotificationSettings, error) {
	const q = `INSERT INTO notification_settings
		(user_id, channel, chargeback_new, chargeback_result, prevention_new, daily_digest, weekly_report)
		VALUES ($1, $2, $3, $4, $5, $6, $7)
		ON CONFLICT (user_id) DO UPDATE SET
			channel = EXCLUDED.channel,
			chargeback_new = EXCLUDED.chargeback_new,
			chargeback_result = EXCLUDED.chargeback_result,
			prevention_new = EXCLUDED.prevention_new,
			daily_digest = EXCLUDED.daily_digest,
			weekly_report = EXCLUDED.weekly_report,
			updated_at = now()
		RETURNING ` + notificationSettingsCols
	row := r.pool.QueryRow(ctx, q,
		s.UserID, s.Channel, s.ChargebackNew, s.ChargebackResult, s.PreventionNew, s.DailyDigest, s.WeeklyReport)
	out, err := scanNotificationSettings(row)
	if err != nil {
		return nil, fmt.Errorf("upsert notification settings: %w", mapDBError(err))
	}
	return out, nil
}
